name: create_dart
version: 0.1.9
author: Federico Omoto <federico.omoto@gmail.com>
description: A port of the CreateJS library to Dart.
homepage: https://github.com/FedeOmoto/CreateDart
environment:
  sdk: '>=1.4.0'
dependencies:
  browser: '>=0.10.0 <=0.11.0'
